---
title: My dynamic report
output: html_fragment
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, error=FALSE)

```

```{css}

h2 {
  color: #2c7fb8;
}

```

## What's going on with this data?

```{r}
library(tidyverse)

# Load data
logged_data <- read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vSNQ_Q2cRWmmlPRI_-iwKFnTyoMR3uuZppOuuwO5gZ2Q-YincJ7MNxjPDIEjOxOGs_VPUGPlhUR1pdn/pub?output=csv")

# Rename variables
latest_data <- logged_data %>%
  rename(
    cost = 'How much did you spend on lunch today?',
    location = 'Where did you get your lunch?',
    time = 'What time did you have lunch?'
  )

# Summary values
avg_cost <- mean(latest_data$cost)
max_cost <- max(latest_data$cost)
min_cost <- min(latest_data$cost)

cost_location <- latest_data %>%
  ggplot() +
    geom_bar(aes(x = cost, fill = location)) +
  labs(
    title = "Distribution of Lunch Costs by Location",
    subtitle = "How much students spend on lunch across different locations",
    caption = "Survey data collected by student at University of Auckland",
    x = "Cost of Lunch (NZD)",
    y = "Number of lunches"
  ) 

cost_time <- latest_data %>%
  ggplot() +
    geom_bar(aes(x = cost, fill = time)) +
  labs(
    title = "Distribution of Lunch Costs by Time",
    subtitle = "How much students spend on lunch across different times of the day",
    caption = "Survey data collected by student at University of Auckland",
    x = "Cost of Lunch (NZD)",
    y = "Number of lunches"
  ) 
print(cost_location)
print(cost_time)

paste(
  "On average, students spend ", round(avg_cost, 2),
  " NZD on lunch. The maximum recorded cost is ", max_cost,
  " NZD, while the minimum is ", min_cost, " NZD."
)
```
